version: 2

jobs:
  build:
    working_directory: /home/circleci/microcosm
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn bootstrap
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn flow
      - run: yarn lint
      - run: sudo apt-get -y -qq install awscli
      - run: yarn deploy
      - run: yarn test:cov --ci
      - run: yarn report-coverage
      - run: yarn test:prod --ci
